export default {
    GET_CITIES_REQUEST: "GET_CITIES_REQUEST",
    GET_CITIES_SUCCESS: "GET_CITIES_SUCCESS",
    GET_CITIES_FAILURE: "GET_CITIES_FAILURE",
    GET_CURRENT_CITY_REQUEST: "GET_CURRENT_CITY_REQUEST",
    GET_CURRENT_CITY_SUCCESS: "GET_CURRENT_CITY_SUCCESS",
    GET_CURRENT_CITY_FAILURE: "GET_CURRENT_CITY_FAILURE",
}