export default {
    GET_CENTERS_ID_REQUEST:"GET_CENTERS_ID_REQUEST",
    GET_CENTERS_ID_SUCCESS:"GET_CENTERS_ID_SUCCESS",
    GET_CENTERS_ID_FAILURE:"GET_CENTERS_ID_FAILURE",
    GET_CURRENT_CENTER_REQUEST:"GET_CURRENT_CENTER_REQUEST",
    GET_CURRENT_CENTER_SUCCESS:"GET_CURRENT_CENTER_SUCCESS",
    GET_CURRENT_CENTER_FAILURE:"GET_CURRENT_CENTER_FAILURE",
}